---
title: "Plotly Examples"
output: 
  html_document:
    toc: true
    toc_float: true

---

# Loading data

We're gonna look at the NYC Airbnb data

```{r}
library(tidyverse)
library(plotly)
```


```{r}
nyc_airbnb = 
  read_csv("./data for plotly/nyc_airbnb.csv") %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price%in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
```


# Plotly plots

## scatterplots

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $ ", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    alpha = 0.5, type = "scatter", mode = "markers")

```

## boxplot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood,price)) %>% 
  plot_ly(
    y = ~price, x = ~neighbourhood, color = ~neighbourhood,
    type = "box", colors = "viridis")

```

## bar plot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood,n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood, 
    colors = "viridis", type = "bar")
```

# ggplotly

```{r}
ggp_scatter = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

#create an interactive version of ggplot (uglier tho)
ggplotly(ggp_scatter)


```





